# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e83119782c49319a27700dfba7fc6309a0786e4c791c80182a1e179f49f57ad8c4f7755d375fb256b7cf123af6b38f6bf099f0e5d4e5b2362a9ce30800d015b1

test:
  secret_key_base: 52e3654b51438565ac231256029443885ddfcfba6c4f9820641a3f0e2d4b16a7113a3240d4fe8766925de43deb51dc3ef560dede59916e7f6db22346aace03ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
